const obj = {
  services: [
    {
      service: 0,
      serviceType: 0,
      title: "Resume Services",
      short: "",
      long: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum laboriosam debitis minima nesciunt, architecto repellendus quia facilis et, veniam quae necessitatibus assumenda! Enim dicta omnis velit nesciunt culpa incidunt totam commodi, molestiae fugit id eligendi alias necessitatibus in impedit aspernatur ut iste minus? Omnis suscipit praesentium aliquid ab vitae esse expedita, sit, exercitationem repudiandae quas repellat voluptatum culpa obcaecati dolorem.",
      notes: "",
      services: [3, 4, 5, 6, 7],
      questions: [0, 5, 6, 7, 8],
    },
    {
      service: 1,
      serviceType: 0,
      title: "Resume Services",
      short: 'Exculisve to Clients who availed the "New Resume Service"',
      long: "",
      notes: "",
      services: [3, 4, 5, 6, 7],
      questions: [0, 5, 6, 7, 8],
    },
    {
      service: 2,
      serviceType: 0,
      title: "Resume Services",
      short: "",
      long: "",
      notes: "",
      services: [3, 4, 5, 6, 7, 8, 9],
      questions: [11],
    },
    {
      service: 3,
      serviceType: 1,
      title: "Other Services",
      short: "Government / Public Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3],
    },
    {
      service: 4,
      serviceType: 1,
      title: "Other Services",
      short: "Private Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3],
    },
    {
      service: 5,
      serviceType: 1,
      title: "Other Services",
      short: "Government / Public Sector",
      long: "",
      notes: "",
      services: [],
      questions: [1, 2, 3],
    },
    {
      service: 6,
      serviceType: 1,
      title: "Other Services",
      short:
        "A customised Selection Criteria highlighting your qualities, skills, abilities and knowledge",
      long: "Key selection criteria (KSC) are typically used in the Australian Public Sector by Government agencies across all levels, from Local and State to Federal, as well as in the education and not-for-profit sector. A well-written, correctly structured selection criteria statement that showcases your skills, knowledge, qualifications and achievements is your key to getting noticed and securing an interview.\r\n\r\nEach selection criteria that we write is customised for you and to the role. We use appropriate keywords and specific examples that accurately respond to the questions, while taking into account the role description and the Integrated Leadership System (ILS), which is the APS capability framework. When responding to the selection criteria, we make sure that each answer is maximum half a page long (in between 250-300 words), as the selection panel often has limited time to go through every applicant.",
      notes: "",
      services: [],
      questions: [4],
    },
    {
      service: 7,
      serviceType: 2,
      title: "Other Services",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
    {
      service: 8,
      serviceType: 2,
      title: "",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
    {
      service: 9,
      serviceType: 2,
      title: "",
      short: "",
      long: "",
      notes: "",
      services: [],
      questions: [],
    },
  ],
  questions: [
    {
      question: 0,
      questionType: 0,
      notes: [
        "Include all jobs (e.g., roles in irrelevant sectors or industries, overseas experience, part-time, contract, casual, project-based).",
        "For Nursing/Social Work, include placements",
      ],
      responses: [0, 1, 2],
    },
    {
      question: 1,
      questionType: 1,
      notes: [""],
      responses: [3, 4, 15],
    },
    {
      question: 2,
      questionType: 2,
      notes: [""],
      responses: [5, 6, 7, 8],
    },
    {
      question: 3,
      questionType: 2,
      notes: [""],
      responses: [9, 10, 11, 12, 13],
    },
    {
      question: 4,
      questionType: 1,
      notes: [""],
      responses: [5, 6, 7, 20, 21],
    },
    {
      question: 5,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 6,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 7,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 8,
      questionType: 0,
      notes: [""],
      responses: [14, 15],
    },
    {
      question: 9,
      questionType: 3,
      notes: [""],
      responses: [],
    },
    {
      question: 10,
      questionType: 3,
      notes: [""],
      responses: [16, 17, 18, 19],
    },
    {
      question: 11,
      questionType: 0,
      notes: [""],
      responses: [5, 6, 7, 20, 21],
    },
  ],
  responses: [
    {
      reponses: 0,
      followup: [],
    },
    {
      reponses: 1,
      followup: [],
    },
    {
      reponses: 2,
      followup: [],
    },
    {
      reponses: 3,
      followup: [2],
    },
    {
      reponses: 4,
      followup: [3],
    },
    {
      reponses: 5,
      followup: [],
    },
    {
      reponses: 6,
      followup: [],
    },
    {
      reponses: 7,
      followup: [],
    },
    {
      reponses: 8,
      followup: [],
    },
    {
      reponses: 9,
      followup: [],
    },
    {
      reponses: 10,
      followup: [],
    },
    {
      reponses: 11,
      followup: [],
    },
    {
      reponses: 12,
      followup: [],
    },
    {
      reponses: 13,
      followup: [],
    },
    {
      reponses: 14,
      followup: [],
    },
    {
      reponses: 15,
      followup: [],
    },
    {
      reponses: 16,
      followup: [],
    },
    {
      reponses: 17,
      followup: [],
    },
    {
      reponses: 18,
      followup: [],
    },
    {
      reponses: 19,
      followup: [],
    },
    {
      reponses: 20,
      followup: [],
    },
    {
      reponses: 21,
      followup: [],
    },
  ],
  indices: {
    serviceType: ["Resume", "Other", "Addon"],
    serviceList: [
      "New Resume",
      "Resume Editing",
      "Resume Update",
      "Pitch / Statement of Claims / Response Document",
      "Cover Letter (Private Sector)",
      "Cover Letter (Government/ Public Agency)",
      "Selection Criteria",
      "LinkedIn Profile (Add-on only)",
      "LinkedIn Profile Update (Add-on only)",
      "Cover Letter Update (Add-on only)",
    ],
    questionType: ["Generic", "Specific", "Followup", "Closing"],
    questionList: [
      "How many years of experience do you have in total?",
      "Is there a page or word limit to your cover letter, pitch, statement or response?",
      "What is the page limit?",
      "What is the word limit?",
      "How many selection criteria do you need responses to?",
      "Is your current job in? retail, hospitality, trades, services and/or admin support?",
      "Have you had experience supervising or managing staff?",
      "Are you a senior leader, C-level executive, GM, Director, EL, SES?",
      "Are you a Doctor, Lawyer or Engineer?",
      "How soon do you need the final copy of your documents?",
      "Please fill out the form below to receive your quotation. ",
      "How many new roles do you need to add to the resume we previously prepared for you?",
    ],
    responseList: [
      "Less Than 2 Years",
      "2-5 Years",
      "More than 5",
      "Yes, page limit",
      "Yes, word limit",
      "One (1)",
      "Two (2)",
      "Three (3)",
      "More Than Three",
      "500 and Below",
      "600 - 1,000",
      "1,100 - 1,500",
      "1,600 - 2,000",
      "2,000 - Above",
      "Yes",
      "No",
      "Enter a date",
      "First Name:",
      "Family Name:",
      "Email:",
      "Four (4)",
      "Five (5)",
    ],
    responseType: ["Radio", "Checkbox", "Number", "Text", "Date"],
  },
};

let holidays = [
  {
    summary: "New Year's Day",
    description: "Public holiday",
    start: "2023-01-01",
    end: "2023-01-02",
  },
  {
    summary: "Day off for New Year's Day (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, Cocos and Keeling Islands, Christmas Island, New South Wales, Northern Territory, Queensland, South Australia, Tasmania, Victoria, Western Australia",
    start: "2023-01-02",
    end: "2023-01-03",
  },
  {
    summary: "Lunar New Year (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2023-01-22",
    end: "2023-01-23",
  },
  {
    summary: "Lunar New Year Holiday (Day 2) (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2023-01-23",
    end: "2023-01-24",
  },
  {
    summary: "Australia Day",
    description: "Public holiday",
    start: "2023-01-26",
    end: "2023-01-27",
  },
  {
    summary: "Royal Hobart Regatta (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2023-02-13",
    end: "2023-02-14",
  },
  {
    summary: "Labour Day (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2023-03-06",
    end: "2023-03-07",
  },
  {
    summary: "Eight Hours Day (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2023-03-13",
    end: "2023-03-14",
  },
  {
    summary: "Labour Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-03-13",
    end: "2023-03-14",
  },
  {
    summary: "Adelaide Cup (South Australia)",
    description: "Public holiday in South Australia",
    start: "2023-03-13",
    end: "2023-03-14",
  },
  {
    summary: "Canberra Day (Australian Capital Territory)",
    description: "Public holiday in Australian Capital Territory",
    start: "2023-03-13",
    end: "2023-03-14",
  },
  {
    summary: "Harmony Day",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2023-03-21",
    end: "2023-03-22",
  },
  {
    summary: "Daylight Saving Time ends",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2023-04-02",
    end: "2023-04-03",
  },
  {
    summary: "Self Determination Day (Cocos and Keeling Islands)",
    description: "Public holiday in Cocos and Keeling Islands",
    start: "2023-04-06",
    end: "2023-04-07",
  },
  {
    summary: "Good Friday (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-04-07",
    end: "2023-04-08",
  },
  {
    summary: "Holy Saturday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Northern Territory, Queensland, South Australia, Victoria, Heard and McDonald Islands",
    start: "2023-04-08",
    end: "2023-04-09",
  },
  {
    summary: "Easter Monday",
    description: "Public holiday",
    start: "2023-04-10",
    end: "2023-04-11",
  },
  {
    summary: "Easter Tuesday (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2023-04-11",
    end: "2023-04-12",
  },
  {
    summary: "Hari Raya Puasa (regional holiday)",
    description:
      "Public holiday in Cocos and Keeling Islands, Christmas Island",
    start: "2023-04-22",
    end: "2023-04-23",
  },
  {
    summary: "Day off for Hari Raya Puasa (regional holiday)",
    description:
      "Public holiday in Cocos and Keeling Islands, Christmas Island",
    start: "2023-04-24",
    end: "2023-04-25",
  },
  {
    summary: "ANZAC Day",
    description: "Public holiday",
    start: "2023-04-25",
    end: "2023-04-26",
  },
  {
    summary: "ANZAC Day Observed (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-04-25",
    end: "2023-04-26",
  },
  {
    summary: "Labour Day (Queensland)",
    description: "Public holiday in Queensland",
    start: "2023-05-01",
    end: "2023-05-02",
  },
  {
    summary: "May Day (Northern Territory)",
    description: "Public holiday in Northern Territory",
    start: "2023-05-01",
    end: "2023-05-02",
  },
  {
    summary: "Reconciliation Day (Australian Capital Territory)",
    description: "Public holiday in Australian Capital Territory",
    start: "2023-05-29",
    end: "2023-05-30",
  },
  {
    summary: "Western Australia Day (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2023-06-05",
    end: "2023-06-06",
  },
  {
    summary: "King's Birthday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Northern Territory, South Australia, Tasmania, Victoria, Cocos and Keeling Islands, Heard and McDonald Islands",
    start: "2023-06-12",
    end: "2023-06-13",
  },
  {
    summary: "Hari Raya Haji (regional holiday)",
    description:
      "Public holiday in Cocos and Keeling Islands, Christmas Island",
    start: "2023-06-29",
    end: "2023-06-30",
  },
  {
    summary: "Northern Territory Picnic Day (Northern Territory)",
    description: "Public holiday in Northern Territory",
    start: "2023-08-07",
    end: "2023-08-08",
  },
  {
    summary: "New South Wales Bank Holiday (New South Wales)",
    description: "Public holiday in New South Wales",
    start: "2023-08-07",
    end: "2023-08-08",
  },
  {
    summary: "Royal National Agricultural Show Day Queensland (Queensland)",
    description: "Public holiday in Queensland",
    start: "2023-08-16",
    end: "2023-08-17",
  },
  {
    summary: "King's Birthday (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2023-09-25",
    end: "2023-09-26",
  },
  {
    summary: "Hari Maulad Nabi (Cocos and Keeling Islands)",
    description: "Public holiday in Cocos and Keeling Islands",
    start: "2023-09-27",
    end: "2023-09-28",
  },
  {
    summary: "Friday before the AFL Grand Final (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-09-29",
    end: "2023-09-30",
  },
  {
    summary: "Daylight Saving Time starts",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2023-10-01",
    end: "2023-10-02",
  },
  {
    summary: "Labour Day (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, South Australia",
    start: "2023-10-02",
    end: "2023-10-03",
  },
  {
    summary: "Territory Day (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2023-10-02",
    end: "2023-10-03",
  },
  {
    summary: "Royal Hobart Show (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2023-10-26",
    end: "2023-10-27",
  },
  {
    summary: "Recreation Day (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2023-11-06",
    end: "2023-11-07",
  },
  {
    summary: "Melbourne Cup Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-11-07",
    end: "2023-11-08",
  },
  {
    summary: "Remembrance Day",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2023-11-11",
    end: "2023-11-12",
  },
  {
    summary: "Christmas Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2023-12-25",
    end: "2023-12-26",
  },
  {
    summary: "Proclamation Day (South Australia)",
    description: "Public holiday in South Australia",
    start: "2023-12-26",
    end: "2023-12-27",
  },
  {
    summary: "Boxing Day",
    description: "Public holiday",
    start: "2023-12-26",
    end: "2023-12-27",
  },
  {
    summary: "New Year's Day",
    description: "Public holiday",
    start: "2024-01-01",
    end: "2024-01-02",
  },
  {
    summary: "Australia Day",
    description: "Public holiday",
    start: "2024-01-26",
    end: "2024-01-27",
  },
  {
    summary: "Lunar New Year (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2024-02-10",
    end: "2024-02-11",
  },
  {
    summary: "Lunar New Year Holiday (Day 2) (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2024-02-11",
    end: "2024-02-12",
  },
  {
    summary: "Royal Hobart Regatta (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2024-02-12",
    end: "2024-02-13",
  },
  {
    summary: "Labour Day (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2024-03-04",
    end: "2024-03-05",
  },
  {
    summary: "Canberra Day (Australian Capital Territory)",
    description: "Public holiday in Australian Capital Territory",
    start: "2024-03-11",
    end: "2024-03-12",
  },
  {
    summary: "Labour Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-03-11",
    end: "2024-03-12",
  },
  {
    summary: "Adelaide Cup (South Australia)",
    description: "Public holiday in South Australia",
    start: "2024-03-11",
    end: "2024-03-12",
  },
  {
    summary: "Eight Hours Day (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2024-03-11",
    end: "2024-03-12",
  },
  {
    summary: "Harmony Day",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2024-03-21",
    end: "2024-03-22",
  },
  {
    summary: "Good Friday (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-03-29",
    end: "2024-03-30",
  },
  {
    summary: "Holy Saturday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Northern Territory, Queensland, South Australia, Victoria, Heard and McDonald Islands",
    start: "2024-03-30",
    end: "2024-03-31",
  },
  {
    summary: "Easter Sunday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Queensland, Victoria, Western Australia",
    start: "2024-03-31",
    end: "2024-04-01",
  },
  {
    summary: "Easter Monday",
    description: "Public holiday",
    start: "2024-04-01",
    end: "2024-04-02",
  },
  {
    summary: "Easter Tuesday (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2024-04-02",
    end: "2024-04-03",
  },
  {
    summary: "Self Determination Day (Cocos and Keeling Islands)",
    description: "Public holiday in Cocos and Keeling Islands",
    start: "2024-04-06",
    end: "2024-04-07",
  },
  {
    summary: "Daylight Saving Time ends",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2024-04-07",
    end: "2024-04-08",
  },
  {
    summary: "Day off for Self Determination Day (Cocos and Keeling Islands)",
    description: "Public holiday in Cocos and Keeling Islands",
    start: "2024-04-08",
    end: "2024-04-09",
  },
  {
    summary: "Hari Raya Puasa (regional holiday)",
    description:
      "Public holiday in Cocos and Keeling Islands, Christmas Island",
    start: "2024-04-10",
    end: "2024-04-11",
  },
  {
    summary: "ANZAC Day",
    description: "Public holiday",
    start: "2024-04-25",
    end: "2024-04-26",
  },
  {
    summary: "ANZAC Day Observed (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-04-25",
    end: "2024-04-26",
  },
  {
    summary: "Labour Day (Queensland)",
    description: "Public holiday in Queensland",
    start: "2024-05-06",
    end: "2024-05-07",
  },
  {
    summary: "May Day (Northern Territory)",
    description: "Public holiday in Northern Territory",
    start: "2024-05-06",
    end: "2024-05-07",
  },
  {
    summary: "Reconciliation Day (Australian Capital Territory)",
    description: "Public holiday in Australian Capital Territory",
    start: "2024-05-27",
    end: "2024-05-28",
  },
  {
    summary: "Western Australia Day (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2024-06-03",
    end: "2024-06-04",
  },
  {
    summary: "King's Birthday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Northern Territory, South Australia, Tasmania, Victoria, Cocos and Keeling Islands, Heard and McDonald Islands",
    start: "2024-06-10",
    end: "2024-06-11",
  },
  {
    summary: "Hari Raya Haji (regional holiday)",
    description:
      "Public holiday in Cocos and Keeling Islands, Christmas Island",
    start: "2024-06-17",
    end: "2024-06-18",
  },
  {
    summary: "Northern Territory Picnic Day (Northern Territory)",
    description: "Public holiday in Northern Territory",
    start: "2024-08-05",
    end: "2024-08-06",
  },
  {
    summary: "New South Wales Bank Holiday (New South Wales)",
    description: "Public holiday in New South Wales",
    start: "2024-08-05",
    end: "2024-08-06",
  },
  {
    summary: "Royal National Agricultural Show Day Queensland (Queensland)",
    description: "Public holiday in Queensland",
    start: "2024-08-14",
    end: "2024-08-15",
  },
  {
    summary: "Hari Maulad Nabi (Cocos and Keeling Islands)",
    description: "Public holiday in Cocos and Keeling Islands",
    start: "2024-09-16",
    end: "2024-09-17",
  },
  {
    summary: "Friday before the AFL Grand Final (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-09-27",
    end: "2024-09-28",
  },
  {
    summary: "Daylight Saving Time starts",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2024-10-06",
    end: "2024-10-07",
  },
  {
    summary: "Territory Day (Christmas Island)",
    description: "Public holiday in Christmas Island",
    start: "2024-10-07",
    end: "2024-10-08",
  },
  {
    summary: "Labour Day (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, South Australia",
    start: "2024-10-07",
    end: "2024-10-08",
  },
  {
    summary: "Royal Hobart Show (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2024-10-24",
    end: "2024-10-25",
  },
  {
    summary: "Recreation Day (Tasmania)",
    description: "Public holiday in Tasmania",
    start: "2024-11-04",
    end: "2024-11-05",
  },
  {
    summary: "Melbourne Cup Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-11-05",
    end: "2024-11-06",
  },
  {
    summary: "Remembrance Day",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2024-11-11",
    end: "2024-11-12",
  },
  {
    summary: "Christmas Day (Victoria)",
    description: "Public holiday in Victoria",
    start: "2024-12-25",
    end: "2024-12-26",
  },
  {
    summary: "Proclamation Day (South Australia)",
    description: "Public holiday in South Australia",
    start: "2024-12-26",
    end: "2024-12-27",
  },
  {
    summary: "Boxing Day",
    description: "Public holiday",
    start: "2024-12-26",
    end: "2024-12-27",
  },
  {
    summary: "King's Birthday (Queensland)",
    description: "Public holiday in Queensland",
    start: "2023-10-02",
    end: "2023-10-03",
  },
  {
    summary: "King's Birthday (Queensland)",
    description: "Public holiday in Queensland",
    start: "2024-10-07",
    end: "2024-10-08",
  },
  {
    summary: "Easter Sunday (regional holiday)",
    description:
      "Public holiday in Australian Capital Territory, New South Wales, Queensland, Victoria, Western Australia",
    start: "2023-04-09",
    end: "2023-04-10",
  },
  {
    summary: "The Coronation of King Charles III",
    description:
      "Observance\nTo hide observances, go to Google Calendar Settings > Holidays in Australia",
    start: "2023-05-06",
    end: "2023-05-07",
  },
  {
    summary: "Christmas Eve (regional holiday)",
    description:
      "Public holiday in Northern Territory, Queensland, South Australia",
    start: "2023-12-24",
    end: "2023-12-25",
  },
  {
    summary: "New Year's Eve (regional holiday)",
    description: "Public holiday in Northern Territory, South Australia",
    start: "2024-12-31",
    end: "2025-01-01",
  },
  {
    summary: "King's Birthday (Western Australia)",
    description: "Public holiday in Western Australia",
    start: "2024-09-23",
    end: "2024-09-24",
  },
  {
    summary: "New Year's Eve (regional holiday)",
    description: "Public holiday in Northern Territory, South Australia",
    start: "2023-12-31",
    end: "2024-01-01",
  },
  {
    summary: "Christmas Eve (regional holiday)",
    description:
      "Public holiday in Northern Territory, Queensland, South Australia",
    start: "2024-12-24",
    end: "2024-12-25",
  },
];
